discord:
  - discord_token: token
openai:
  - openai_key: key
  - gpt_model: gpt-3.5-turbo
database:
  - db_enabled: true
  - db_name: database.db
blacklist:
  - blacklist_enabled: true
  - blacklist_db: database.db
